version: '2.1'

services:
  pihole:
    # Network-wide ad blocking - https://pi-hole.net/
    extends:
      service: pihole
      file: pihole/docker-compose.yaml
    networks:
      home:
        ipv4_address: 192.168.1.201

  homebridge:
    # Run Homebridge to emulate iOS HomeKit API
    extends:
      service: homebridge
      file: homebridge/docker-compose.yaml

  smokeping:
    # Track network latency
    extends:
      service: smokeping
      file: smokeping/docker-compose.yaml

  simplemonitor:
    # Network monitoring
    extends:
      service: simplemonitor
      file: simplemonitor-docker/docker-compose.yaml

networks:
  home:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: "192.168.1.0/24"
          gateway: "192.168.1.1"
          ip_range: "192.168.1.192/28"

