version: '2.1'

services:
  pihole:
    # Network-wide ad blocking - https://pi-hole.net/
    extends:
      service: pihole
      file: pihole/docker-compose.yaml
    networks:
      home:
        ipv4_address: 192.168.1.201

