version: '2.1'

services:
  unbound:
    container_name: unbound
    image: waywardone/unbound:latest
    build: .
    hostname: unbound
    mac_address: d0:ca:ab:cd:ef:06
    ports:
      - 53/tcp
      - 53/udp
    networks:
      home:
        ipv4_address: 192.168.1.6
    restart: always
